// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateProduct struct {
	Nama  string `json:"nama"`
	Stok  string `json:"stok"`
	Harga string `json:"harga"`
}

type DeleteProduct struct {
	DeletedProductID string `json:"deletedProductId"`
}

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Product struct {
	ID    string `json:"_id"`
	Nama  string `json:"nama"`
	Stok  string `json:"stok"`
	Harga string `json:"harga"`
}

type Query struct {
}

type UpdateProduct struct {
	Nama  string `json:"nama"`
	Stok  string `json:"stok"`
	Harga string `json:"harga"`
}

type User struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
